# Use settings similar to default and YAS styles, which are less conservative than the julia-vscode
# extension defaults (see: https://domluna.github.io/JuliaFormatter.jl/stable/style/#Style,
#                          https://domluna.github.io/JuliaFormatter.jl/stable/yas_style/)
always_for_in=true
whitespace_ops_in_indices=true
remove_extra_newlines=true
import_to_using=true
pipe_to_function_call=true
short_to_long_function_def=true
always_use_return=true
whitespace_in_kwargs=false
separate_kwargs_with_semicolon=true
# join_lines_based_on_source=true
# style="yas"